---
title: "Lab1"
author: vov41234567890@yandex.ru
date: "2025-11-18"
format: md
output-file: README.md
---

# Цели работы

1\. Развить практические навыки использования и применения языка R для обработки данных

2\. Развить навыки работы в Rstudio IDE:установка пакетов,работа с проектами в Rstudio,настройка и работа с Git

## Установить интерпретатор R 

```{R}
sessionInfo()
```

## Заходим в окружение swirl

```         
swirl::swirl()
```

## Изучаем синтактсис и записываем пример

```         
y \<- x - 3 y \[1\] 9
```

## Присвоение значений переменной

```         
z \<- c(1.1, 9, 3.14)
```

## Запросим хелпу команды

```         
?c
```

## Вывод содержимого

```         
> z \[1\] 1.10 9.00 3.14
```

## Объединение векторов

```         
> c(z, 555, z) \[1\] 1.10 9.00 3.14 555.00 1.10 9.00 3.14
```

## Числовые вектора в арифметических выражениях

```         
> z \* 2 + 100 \[1\] 102.20 118.00 106.28
```

## Возьмем квадратный корень из z - 1 и присвем его новой переменной

```         
> my_sqrt \<- sqrt(z - 1)
```

## Выведем что находится в my_sqrt.

```         
 my_sqrt \[1\] 0.3162278 2.8284271 1.4628739
```

## Создаем новую переменную которая равноа значению z деленное на my_sqrt.

```         
 my_div \<- z/my_sqrt
```

## Выведем что находится в my_div.

```         
> my_div \[1\] 3.478505 3.181981 2.146460
```

## Сложим вектора

```         
> c(1, 2, 3, 4) + c(0, 10) \[1\] 1 12 3 14
```

```         
> c(1, 2, 3, 4) + c(0, 10, 100) \[1\] 1 12 103 4
```

## Определим рабочий каталог

```         
> getwd() \[1\] "/Users/vladimir"
```

## Выведем объекты в рабочем пространстве

```         
> ls() \[1\] "my_div" "my_sqrt" "temp_dir" "x" "y" "z"
```

## Присвоение значения

```         
> x \<- 9
```

## Выведем список всех файлов в рабочем каталоге

```         
> list.files() \[1\] "\# app.py" "app.py" "Applications" "Cisco Packet Tracer 8.2.2"\
> \[5\] "Desktop" "Documents" "Downloads" "edb_pgagent_pg17.app.zip"\
> \[9\] "edb_pgjdbc.app.zip" "edb_psqlodbc.app.zip" "from docx import Document.py" "import matplotlib.py"\
> \[13\] "import pandas as pd.py" "Library" "Movies" "Music"\
> \[17\] "node_modules" "package-lock.json" "package.json" "Pictures"\
> \[21\] "postgresql_17.app.zip" "Postman" "pr_1" "Public"\
> \[25\] "PycharmProjects" "python3" "RiderProjects" "scripts"\
> \[29\] "shop.db" "ssh" "Untitled.ipynb" "untitled.py"\
> \[33\] "Untitled1.ipynb" "Untitled2.ipynb" "venv" "Virtual Machines.localized"
```

## Вывелем хелпу по команде

```         
> ?list.files
```

## Используем функцию args() для определения аргументов list.files().

```         
> args(list.files) function (path = ".", pattern = NULL, all.files = FALSE, full.names = FALSE, recursive = FALSE, ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE) NULL
```

## Присвоем значение текущего рабочего каталога переменной

```         
> old.dir \<- getwd()
```

## Создание каталога

```         
> dir.create("testdir")
```

## Поменяем рабочий каталог

```         
> setwd("testdir")
```

## Создание нового файла

```         
> file.create("mytest.R") \[1\] TRUE
```

## Провекра каталога

```         
> list.files() \[1\] "mytest.R"
```

## Проверка наличия в каталоге файла

```         
> file.exists("mytest.R") \[1\] TRUE
```

## Проверим информацию о файле

```         
> file.info("mytest.R") size isdir mode mtime ctime atime uid gid uname grname mytest.R 0 FALSE 644 2025-11-08 13:25:31 2025-11-08 13:25:31 2025-11-08 13:25:31 501 20 vladimir staff
```

## Поменяем имя файла

```         
> file.rename("mytest.R", "mytest2.R") \[1\] TRUE
```

## Сделать копию файла

```         
> file.copy("mytest2.R", "mytest3.R") \[1\] TRUE
```

## Проверим путь к файлу

```         
> file.path("mytest3.R") \[1\] "mytest3.R"

> file.path("folder1", "folder2") \[1\] "folder1/folder2"
```

## Выводим хелпу команды

```         
> ?dir.create
```

## Создадим директорию

```         
> dir.create(file.path('testdir2', 'testdir3'), recursive = TRUE)
```

## Сменим директорию

```         
> setwd(old.dir)
```

## Создание последовательности чисел различными способами

```         
> 1:20 \[1\] 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20

> pi:10 \[1\] 3.141593 4.141593 5.141593 6.141593 7.141593 8.141593 9.141593

> 15:1 \[1\] 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1

> ?`:`

> seq(1, 20) \[1\] 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20

> seq(0, 10, by=0.5) \[1\] 0.0 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0 8.5 9.0 9.5 10.0

> my_seq \<- seq(5, 10, length=30)

> length(my_seq) \[1\] 30

> 1:length(my_seq) \[1\] 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

> seq(along.with = my_seq) \[1\] 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

> seq_along(my_seq) \[1\] 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

> rep(0, times = 40) \[1\] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

> rep(c(0, 1, 2), times = 10) \[1\] 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2

> rep(c(0, 1, 2), each = 10) \[1\] 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2
```

## Cоздание числового вектора различными способами

```         
> num_vect \<- c(0.5, 55, -10, 6)

> tf \<- num_vect \< 1

> num_vect \>= 6 \[1\] FALSE TRUE FALSE TRUE
```

## Занесем значения в переменную с дальнейшем выводом результата различными способами(работа с символами)

```         
> my_char \<- c("My", "name", "is")

> my_char \[1\] "My" "name" "is"

> paste(my_char, collapse = " ") \[1\] "My name is"

> my_name \<- c(my_char, "Vladimir")

> my_name \[1\] "My" "name" "is" "Vladimir"

> paste(my_name, collapse = " ") \[1\] "My name is Vladimir"

> paste("Hello","world!", sep = " ") \[1\] "Hello world!"

> paste(1:3, c("X", "Y", "Z"), sep = "") \[1\] "1X" "2Y" "3Z"

> paste(LETTERS, 1:4, sep = "-") \[1\] "A-1" "B-2" "C-3" "D-4" "E-1" "F-2" "G-3" "H-4" "I-1" "J-2" "K-3" "L-4" "M-1" "N-2" "O-3" "P-4" "Q-1" "R-2" "S-3" "T-4" \[21\] "U-1" "V-2" "W-3" "X-4" "Y-1" "Z-2"
```

## Работа с NA

```         
> x \<- c(44, NA, 5, NA)

> x \* 3 \[1\] 132 NA 15 NA

> y \<- rnorm(1000)

> z \<- rep(NA, 1000)

> my_data \<- sample(c(y, z), 100)

> my_na \<- is.na(my_data)

> my_na \[1\] TRUE TRUE TRUE TRUE FALSE FALSE TRUE TRUE FALSE TRUE TRUE TRUE TRUE TRUE FALSE TRUE FALSE FALSE FALSE FALSE \[21\] TRUE TRUE TRUE TRUE FALSE FALSE FALSE TRUE TRUE FALSE FALSE TRUE FALSE FALSE TRUE FALSE FALSE TRUE FALSE FALSE \[41\] FALSE TRUE FALSE FALSE TRUE TRUE FALSE FALSE TRUE TRUE FALSE TRUE TRUE FALSE TRUE TRUE TRUE FALSE TRUE TRUE \[61\] FALSE TRUE FALSE FALSE FALSE TRUE FALSE FALSE FALSE TRUE FALSE FALSE FALSE TRUE FALSE FALSE TRUE TRUE TRUE TRUE \[81\] FALSE FALSE TRUE TRUE FALSE FALSE FALSE FALSE FALSE FALSE TRUE TRUE TRUE TRUE FALSE FALSE FALSE FALSE TRUE TRUE

> my_data == NA \[1\] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA \[42\] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA \[83\] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

> my_data \[1\] NA NA NA NA -0.25077729 0.27757137 NA NA 0.60537518 NA \[11\] NA NA NA NA -0.55365208 NA -1.85595991 -0.44746397 -0.17005184 -0.12493809 \[21\] NA NA NA NA -0.01753650 -0.21762172 0.61188338 NA NA -0.61124826 \[31\] 0.43611976 NA -0.65312591 0.47905511 NA -0.74344991 1.56974517 NA -1.14656403 -1.15140371 \[41\] -0.67485767 NA 1.88509689 -0.62184045 NA NA 0.08784532 0.10171022 NA NA \[51\] -1.04843596 NA NA 2.38910415 NA NA NA 0.28477712 NA NA \[61\] 0.91274524 NA 0.04256764 0.27091969 -0.19401365 NA 0.45746758 -0.08820899 2.31329639 NA \[71\] -0.47824339 -0.80540792 -1.19189055 NA -1.50918308 1.45124898 NA NA NA NA \[81\] 0.34088654 -0.80253520 NA NA -0.03922130 0.77903446 -0.61674156 1.67379959 -1.10870907 -1.29516016 \[91\] NA NA NA NA -0.49182878 -1.99013021 1.61917601 1.29780272 NA NA

> 0/0 \[1\] NaN

> Inf - Inf \[1\] NaN
```
